---
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Security Group template for allowing OpenVPN access to LDAP.

Parameters:
  OpenVPNSG:
    Description: SecurityGroup for OpenVPN (output from the OpenVPN CloudFormation script)
    Type: AWS::EC2::SecurityGroup::Id
  LDAPSG:
    Description: SecurityGroup for LDAP (SecurityGroup your LDAP instance is running in e.g. ADOP/C SecurityGroup)
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  SGBaseIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: LDAPSG
      IpProtocol: tcp
      FromPort: '389'
      ToPort: '389'
      SourceSecurityGroupId:
        Ref: OpenVPNSG
...
